/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'apps-agendamentos-agendamentos-index': RouteRecordInfo<'apps-agendamentos-agendamentos-index', '/apps/agendamentos/agendamentos-index', Record<never, never>, Record<never, never>>,
    'apps-clientes-cliente': RouteRecordInfo<'apps-clientes-cliente', '/apps/clientes/cliente', Record<never, never>, Record<never, never>>,
    'apps-clientes-clientes': RouteRecordInfo<'apps-clientes-clientes', '/apps/clientes/clientes', Record<never, never>, Record<never, never>>,
    'apps-comissao-comissao-index': RouteRecordInfo<'apps-comissao-comissao-index', '/apps/comissao/comissao-index', Record<never, never>, Record<never, never>>,
    'apps-config-config': RouteRecordInfo<'apps-config-config', '/apps/config/config', Record<never, never>, Record<never, never>>,
    'apps-crm-campanhas': RouteRecordInfo<'apps-crm-campanhas', '/apps/crm/campanhas', Record<never, never>, Record<never, never>>,
    'apps-crm-chat': RouteRecordInfo<'apps-crm-chat', '/apps/crm/chat', Record<never, never>, Record<never, never>>,
    'apps-crm-config-crm': RouteRecordInfo<'apps-crm-config-crm', '/apps/crm/config-crm', Record<never, never>, Record<never, never>>,
    'apps-crm-configs-tags': RouteRecordInfo<'apps-crm-configs-tags', '/apps/crm/configs/tags', Record<never, never>, Record<never, never>>,
    'apps-crm-configs-zap': RouteRecordInfo<'apps-crm-configs-zap', '/apps/crm/configs/zap', Record<never, never>, Record<never, never>>,
    'apps-crm-funis': RouteRecordInfo<'apps-crm-funis', '/apps/crm/funis', Record<never, never>, Record<never, never>>,
    'apps-crm-modelos': RouteRecordInfo<'apps-crm-modelos', '/apps/crm/modelos', Record<never, never>, Record<never, never>>,
    'apps-crm-modelos-emails': RouteRecordInfo<'apps-crm-modelos-emails', '/apps/crm/modelos-emails', Record<never, never>, Record<never, never>>,
    'apps-crm-modelos-mensagens': RouteRecordInfo<'apps-crm-modelos-mensagens', '/apps/crm/modelos-mensagens', Record<never, never>, Record<never, never>>,
    'apps-crm-negocio': RouteRecordInfo<'apps-crm-negocio', '/apps/crm/negocio', Record<never, never>, Record<never, never>>,
    'apps-crm-new-campanha': RouteRecordInfo<'apps-crm-new-campanha', '/apps/crm/newCampanha', Record<never, never>, Record<never, never>>,
    'apps-crm-segmentacoes': RouteRecordInfo<'apps-crm-segmentacoes', '/apps/crm/segmentacoes', Record<never, never>, Record<never, never>>,
    'apps-estoque-estoque-index': RouteRecordInfo<'apps-estoque-estoque-index', '/apps/estoque/estoque-index', Record<never, never>, Record<never, never>>,
    'apps-fluxo-fluxos-index': RouteRecordInfo<'apps-fluxo-fluxos-index', '/apps/fluxo/fluxos-index', Record<never, never>, Record<never, never>>,
    'apps-lembretes-lembretes-index': RouteRecordInfo<'apps-lembretes-lembretes-index', '/apps/lembretes/lembretes-index', Record<never, never>, Record<never, never>>,
    'apps-pagamentos-despesas': RouteRecordInfo<'apps-pagamentos-despesas', '/apps/pagamentos/despesas', Record<never, never>, Record<never, never>>,
    'apps-pagamentos-pagamentos-index': RouteRecordInfo<'apps-pagamentos-pagamentos-index', '/apps/pagamentos/pagamentos-index', Record<never, never>, Record<never, never>>,
    'apps-pagamentos-pagar': RouteRecordInfo<'apps-pagamentos-pagar', '/apps/pagamentos/pagar', Record<never, never>, Record<never, never>>,
    'apps-pagamentos-receber': RouteRecordInfo<'apps-pagamentos-receber', '/apps/pagamentos/receber', Record<never, never>, Record<never, never>>,
    'apps-pagamentos-saida': RouteRecordInfo<'apps-pagamentos-saida', '/apps/pagamentos/saida', Record<never, never>, Record<never, never>>,
    'apps-relatorios-agendamentos-relatorios': RouteRecordInfo<'apps-relatorios-agendamentos-relatorios', '/apps/relatorios/agendamentos-relatorios', Record<never, never>, Record<never, never>>,
    'apps-relatorios-comissoes-relatorios': RouteRecordInfo<'apps-relatorios-comissoes-relatorios', '/apps/relatorios/comissoes-relatorios', Record<never, never>, Record<never, never>>,
    'apps-relatorios-financeiro-relatorios': RouteRecordInfo<'apps-relatorios-financeiro-relatorios', '/apps/relatorios/financeiro-relatorios', Record<never, never>, Record<never, never>>,
    'apps-relatorios-relatorios': RouteRecordInfo<'apps-relatorios-relatorios', '/apps/relatorios/relatorios', Record<never, never>, Record<never, never>>,
    'apps-relatorios-servicos-relatorios': RouteRecordInfo<'apps-relatorios-servicos-relatorios', '/apps/relatorios/servicos-relatorios', Record<never, never>, Record<never, never>>,
    'apps-servicos-servicos': RouteRecordInfo<'apps-servicos-servicos', '/apps/servicos/servicos', Record<never, never>, Record<never, never>>,
    'apps-user-list': RouteRecordInfo<'apps-user-list', '/apps/user/list', Record<never, never>, Record<never, never>>,
    'apps-user-view-id': RouteRecordInfo<'apps-user-view-id', '/apps/user/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-user-view-id-empresa': RouteRecordInfo<'apps-user-view-id-empresa', '/apps/user/view/:id-empresa', { id-empresa: ParamValue<true> }, { id-empresa: ParamValue<false> }>,
    'esqueci-senha': RouteRecordInfo<'esqueci-senha', '/esqueci-senha', Record<never, never>, Record<never, never>>,
    'home': RouteRecordInfo<'home', '/home', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'nova-senha': RouteRecordInfo<'nova-senha', '/novaSenha', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'sem-autorizacao': RouteRecordInfo<'sem-autorizacao', '/sem-autorizacao', Record<never, never>, Record<never, never>>,
    'trocar-empresa': RouteRecordInfo<'trocar-empresa', '/trocar-empresa', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
